-- 国家/地区区号表（区号接口数据源；管理后台也依赖此表）
CREATE TABLE IF NOT EXISTS countries (
    code       VARCHAR(8)  PRIMARY KEY,
    dial_code  VARCHAR(8)  NOT NULL DEFAULT '',
    cn_name    VARCHAR(64) NOT NULL DEFAULT '',
    en_name    VARCHAR(64) NOT NULL DEFAULT '',
    phone_rule VARCHAR(128) NOT NULL DEFAULT '',
    enabled    BOOLEAN     NOT NULL DEFAULT true,
    sort_order INT         NOT NULL DEFAULT 0
);

-- 常用国家区号（幂等，可重复执行）
INSERT INTO countries(code, dial_code, cn_name, en_name, sort_order) VALUES
('CN','86','中国','China',1),
('HK','852','中国香港','Hong Kong',2),
('MO','853','中国澳门','Macao',3),
('TW','886','中国台湾','Taiwan',4),
('US','1','美国','United States',5),
('GB','44','英国','United Kingdom',6),
('JP','81','日本','Japan',7),
('KR','82','韩国','South Korea',8),
('SG','65','新加坡','Singapore',9),
('MY','60','马来西亚','Malaysia',10),
('TH','66','泰国','Thailand',11),
('VN','84','越南','Vietnam',12),
('PH','63','菲律宾','Philippines',13),
('ID','62','印度尼西亚','Indonesia',14),
('IN','91','印度','India',15),
('AU','61','澳大利亚','Australia',16),
('NZ','64','新西兰','New Zealand',17),
('CA','1','加拿大','Canada',18),
('DE','49','德国','Germany',19),
('FR','33','法国','France',20),
('IT','39','意大利','Italy',21),
('ES','34','西班牙','Spain',22),
('NL','31','荷兰','Netherlands',23),
('RU','7','俄罗斯','Russia',24),
('AE','971','阿联酋','United Arab Emirates',25),
('SA','966','沙特阿拉伯','Saudi Arabia',26),
('TR','90','土耳其','Turkey',27),
('BR','55','巴西','Brazil',28),
('MX','52','墨西哥','Mexico',29),
('AR','54','阿根廷','Argentina',30),
('CH','41','瑞士','Switzerland',31),
('SE','46','瑞典','Sweden',32),
('PT','351','葡萄牙','Portugal',33),
('GR','30','希腊','Greece',34),
('PL','48','波兰','Poland',35),
('BE','32','比利时','Belgium',36),
('AT','43','奥地利','Austria',37),
('IE','353','爱尔兰','Ireland',38),
('DK','45','丹麦','Denmark',39),
('FI','358','芬兰','Finland',40),
('NO','47','挪威','Norway',41),
('ZA','27','南非','South Africa',42),
('EG','20','埃及','Egypt',43),
('NG','234','尼日利亚','Nigeria',44),
('PK','92','巴基斯坦','Pakistan',45),
('BD','880','孟加拉国','Bangladesh',46),
('IL','972','以色列','Israel',47),
('UA','380','乌克兰','Ukraine',48),
('CZ','420','捷克','Czech Republic',49)
ON CONFLICT (code) DO NOTHING;
